os: linux
dist: focal
language: c

jobs:
  include:
    - name: "Build Kernel"
      arch: arm64
      script:
        - sudo apt-get update
        - sudo apt-get install -y gcc-aarch64-linux-gnu
        - export ARCH=arm64
        - export CROSS_COMPILE=aarch64-linux-gnu-
        - export PATH=$PATH:/path/to/android/clang/bin  # Replace with the actual path to Android Clang
        - make vendor/spes_perf-defconfig
        - make -j$(nproc)

