os: linux
dist: focal
language: c

jobs:
  include:
    - name: "Build Kernel"
      arch: amd64
      script:
        - sudo apt-get update
        - sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        - sudo apt-get remove -y *cuda*
        - git clone --depth=1 -b 14 https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone
        - ls -d $PWD/*
        - git clone --depth=1 https://github.com/muralivijay/kernel_xiaomi_sm6225
        - export ARCH=arm64
        - export PATH=/home/travis/build/shifty-d/ci-tests/android_prebuilts_clang-standalone/bin:$PATH
        - clang -v
        - cd kernel_xiaomi_sm6225
        - make vendor/spes-perf_defconfig
        - echo | make -j$(nproc) CC=clang LD=ld.lld AS=llvm-as AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 Image.gz dtbo.img
